src/java/com/motogp/controlador/PilotoController.java
package com.motogp.controlador;

import com.motogp.controlador.util.FacesUtils;
import com.motogp.entidades.Piloto;
import com.motogp.controlador.util.JsfUtil;
import com.motogp.controlador.util.JsfUtil.PersistAction;
import com.motogp.entidades.Motocicleta;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("pilotoController")
@SessionScoped
public class PilotoController implements Serializable {

    @EJB
    private com.motogp.controlador.PilotoFacade ejbFacade;
    private List<Piloto> items = null;
    private Piloto selected;

    public PilotoController() {
    }

    public Piloto getSelected() {
        return selected;
    }

    public void setSelected(Piloto selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PilotoFacade getFacade() {
        return ejbFacade;
    }

    public Piloto prepareCreate() {
        selected = new Piloto();
        initializeEmbeddableKey();
        return selected;
    }
    public boolean validarUsoMotocicleta(Motocicleta motoBuscar)
    {
        for(Piloto ciclo:items)
        {
            if(ciclo.getFkMotocicleta().getCodigo().equals(motoBuscar.getCodigo()))
            {
                return true;
            }
        }
        return  false ; 
    }

    public void create() {
        if(!validarUsoMotocicleta(selected.getFkMotocicleta()))
        {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("PilotoCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
        }
        else
        {
            JsfUtil.addErrorMessage("La motocicleta ya esta en uso");
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("PilotoUpdated"));
    }

    public void destroy() {
        ClasificacionController clasifController= 
                (ClasificacionController) 
                FacesUtils.getManagedBean("clasificacionController");
        if(clasifController.getLista().getCabeza()==null)
        {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("PilotoDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }
        else
        {
            FacesUtils.addErrorMessage("No puede Eliminar ya existe una clasificación en curso");
        }
    }
    

    public List<Piloto> getItems() {
//       if (items == null) {
           items = getFacade().findAll();
//        
//}

        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Piloto getPiloto(java.lang.String id) {
        return getFacade().find(id);
    }

    public List<Piloto> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Piloto> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Piloto.class)
    public static class PilotoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PilotoController controller = (PilotoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pilotoController");
            return controller.getPiloto(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Piloto) {
                Piloto o = (Piloto) object;
                return getStringKey(o.getNumero());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Piloto.class.getName()});
                return null;
            }
        }

    }

}

web/piloto/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PilotoCreateDlg" widgetVar="PilotoCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePilotoTitle}">
            <h:form id="PilotoCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{pilotoController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_numero}" for="numero" />
                        <p:inputText id="numero" value="#{pilotoController.selected.numero}" title="#{bundle.CreatePilotoTitle_numero}" required="true" requiredMessage="#{bundle.CreatePilotoRequiredMessage_numero}"/>
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{pilotoController.selected.nombre}" title="#{bundle.CreatePilotoTitle_nombre}" required="true" requiredMessage="#{bundle.CreatePilotoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_edad}" for="edad" />
                        <p:inputText id="edad" value="#{pilotoController.selected.edad}" title="#{bundle.CreatePilotoTitle_edad}" required="true" requiredMessage="#{bundle.CreatePilotoRequiredMessage_edad}"/>
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_fkEquipo}" for="fkEquipo" />
                        <p:selectOneMenu id="fkEquipo" value="#{pilotoController.selected.fkEquipo}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkEquipo}">
                            <f:selectItems value="#{equipoController.itemsAvailableSelectOne}"
                                           var="fkEquipoItem"
                                           itemValue="#{fkEquipoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_fkMotocicleta}" for="fkMotocicleta" />
                        <p:selectOneMenu id="fkMotocicleta" value="#{pilotoController.selected.fkMotocicleta}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkMotocicleta}">
                            <f:selectItems value="#{motocicletaController.itemsAvailableSelectOne}"
                                           var="fkMotocicletaItem"
                                           itemValue="#{fkMotocicletaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePilotoLabel_fkNacionalidad}" for="fkNacionalidad" />
                        <p:selectOneMenu id="fkNacionalidad" value="#{pilotoController.selected.fkNacionalidad}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkNacionalidad}">
                            <f:selectItems value="#{nacionalidadController.itemsAvailableSelectOne}"
                                           var="fkNacionalidadItem"
                                           itemValue="#{fkNacionalidadItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{pilotoController.create}" value="#{bundle.Save}" update="display,:PilotoListForm:datalist,:growl" oncomplete="handleSubmit(args,'PilotoCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PilotoCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/piloto/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PilotoEditDlg" widgetVar="PilotoEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPilotoTitle}">
            <h:form id="PilotoEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{pilotoController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPilotoLabel_numero}" for="numero" />
                        <p:inputText id="numero" value="#{pilotoController.selected.numero}" title="#{bundle.EditPilotoTitle_numero}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_numero}"/>
                        <p:outputLabel value="#{bundle.EditPilotoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{pilotoController.selected.nombre}" title="#{bundle.EditPilotoTitle_nombre}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.EditPilotoLabel_edad}" for="edad" />
                        <p:inputText id="edad" value="#{pilotoController.selected.edad}" title="#{bundle.EditPilotoTitle_edad}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_edad}"/>
                        <p:outputLabel value="#{bundle.EditPilotoLabel_fkEquipo}" for="fkEquipo" />
                        <p:selectOneMenu id="fkEquipo" value="#{pilotoController.selected.fkEquipo}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkEquipo}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{equipoController.itemsAvailableSelectOne}"
                                           var="fkEquipoItem"
                                           itemValue="#{fkEquipoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditPilotoLabel_fkMotocicleta}" for="fkMotocicleta" />
                        <p:selectOneMenu id="fkMotocicleta" value="#{pilotoController.selected.fkMotocicleta}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkMotocicleta}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{motocicletaController.itemsAvailableSelectOne}"
                                           var="fkMotocicletaItem"
                                           itemValue="#{fkMotocicletaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditPilotoLabel_fkNacionalidad}" for="fkNacionalidad" />
                        <p:selectOneMenu id="fkNacionalidad" value="#{pilotoController.selected.fkNacionalidad}" required="true" requiredMessage="#{bundle.EditPilotoRequiredMessage_fkNacionalidad}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{nacionalidadController.itemsAvailableSelectOne}"
                                           var="fkNacionalidadItem"
                                           itemValue="#{fkNacionalidadItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{pilotoController.update}" value="#{bundle.Save}" update="display,:PilotoListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PilotoEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PilotoEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/piloto/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPilotoTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="PilotoListForm">
                <p:panel header="#{bundle.ListPilotoTitle}">
                    <p:dataTable id="datalist" value="#{pilotoController.items}" var="item"
                                 selectionMode="single" selection="#{pilotoController.selected}"
                                 paginator="true"
                                 rowKey="#{item.numero}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_numero}"/>
                            </f:facet>
                            <h:outputText value="#{item.numero}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_edad}"/>
                            </f:facet>
                            <h:outputText value="#{item.edad}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_fkEquipo}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkEquipo.descripcion}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_fkMotocicleta}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkMotocicleta.fkMarca.descripcion} - #{item.fkMotocicleta.color}" />
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPilotoTitle_fkNacionalidad}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkNacionalidad.descripcion}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{pilotoController.prepareCreate}" update=":PilotoCreateForm" oncomplete="PF('PilotoCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PilotoViewForm" oncomplete="PF('PilotoViewDialog').show()" disabled="#{empty pilotoController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PilotoEditForm" oncomplete="PF('PilotoEditDialog').show()" disabled="#{empty pilotoController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{pilotoController.destroy}" update=":growl,datalist" disabled="#{empty pilotoController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/piloto/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PilotoViewDlg" widgetVar="PilotoViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPilotoTitle}">
            <h:form id="PilotoViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{pilotoController.selected != null}">
                        <h:outputText value="#{bundle.ViewPilotoLabel_numero}"/>
                        <h:outputText value="#{pilotoController.selected.numero}" title="#{bundle.ViewPilotoTitle_numero}"/>
                        <h:outputText value="#{bundle.ViewPilotoLabel_nombre}"/>
                        <h:outputText value="#{pilotoController.selected.nombre}" title="#{bundle.ViewPilotoTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewPilotoLabel_edad}"/>
                        <h:outputText value="#{pilotoController.selected.edad}" title="#{bundle.ViewPilotoTitle_edad}"/>
                        <h:outputText value="#{bundle.ViewPilotoLabel_fkEquipo}"/>
                        <h:outputText value="#{pilotoController.selected.fkEquipo}" title="#{bundle.ViewPilotoTitle_fkEquipo}"/>
                        <h:outputText value="#{bundle.ViewPilotoLabel_fkMotocicleta}"/>
                        <h:outputText value="#{pilotoController.selected.fkMotocicleta}" title="#{bundle.ViewPilotoTitle_fkMotocicleta}"/>
                        <h:outputText value="#{bundle.ViewPilotoLabel_fkNacionalidad}"/>
                        <h:outputText value="#{pilotoController.selected.fkNacionalidad}" title="#{bundle.ViewPilotoTitle_fkNacionalidad}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PilotoViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>